#!/usr/bin/env python3
"""Download official Bungie CDN icons for offline Widgetbook / hosts.

Sources:
  - Paths in destiny_official_icons.dart + Next catalogFilterVisuals.ts (meta/frame)
  - Curated weapon item icons in EXTRA_WEAPON_ICONS (fixture catalog art)

Stores under assets/bungie-content/icons/ and regenerates
lib/src/bungie_content_local_assets.g.dart.

Usage (from packages/ui_flutter):
  python tool/fetch_bungie_content_icons.py
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICONS_DIR = ROOT / "assets" / "bungie-content" / "icons"
GEN = ROOT / "lib" / "src" / "bungie_content_local_assets.g.dart"
OFFICIAL_DART = ROOT / "lib" / "src" / "destiny_official_icons.dart"
WEB_FILTERS = (
    ROOT.parents[2]
    / "web"
    / "NextJS"
    / "src"
    / "lib"
    / "destiny"
    / "catalogFilterVisuals.ts"
)

# Fixture / demo weapon plates (basename must match CDN).
# Sourced from DestinyInventoryItemDefinition displayProperties.icon.
EXTRA_WEAPON_ICONS = [
    "/common/destiny2_content/icons/cdfbfd3f098329a367294f191070f8c4.jpg",  # Ace of Spades
    "/common/destiny2_content/icons/a16c0c62d2153cb59ca7dd5565d66d6a.jpg",  # Midnight Coup
    "/common/destiny2_content/icons/d5c1b1c3eaf09bbf7aa5592490c31aa0.jpg",  # Midnight Coup (alt)
    "/common/destiny2_content/icons/161a3f06196563345afeacb46e9df88d.jpg",  # Cerberus+1
    "/common/destiny2_content/icons/04652b3f85434968340359f93de0520b.jpg",  # Ribbontail
    "/common/destiny2_content/icons/dd0ae6e8b9aeccfcbec7d5971c48984c.jpg",  # Unsworn
    "/common/destiny2_content/icons/f45a7d8e52bf0d88bbd43d4354878313.jpg",  # Sunshot
    "/common/destiny2_content/icons/0b7fa10956ee9f16899ce1838c3c0e31.jpg",  # Riskrunner
    "/common/destiny2_content/icons/d936e6dd748647d394afd71110f48b21.jpg",  # Funnelweb
    "/common/destiny2_content/icons/cfc2c246cfd404d749fffbfe3ae3dfec.jpg",  # Dead Man's Tale
    "/common/destiny2_content/icons/2752ee2761149f004df20e78749c1bab.jpg",  # Osteo Striga
    "/common/destiny2_content/icons/c6aa03536fd68b5fca5ad6b83ea0cf1e.jpg",  # Divinity
    "/common/destiny2_content/icons/2a2a95b819312fc6fef728911cfd6fa2.jpg",  # Coldheart
    "/common/destiny2_content/icons/e905d8c17ef5ead5c6f9cd107b4b6f09.jpg",  # Austringer
    "/common/destiny2_content/icons/d526de3389b40131261567496816368e.jpg",  # Igneous Hammer
    "/common/destiny2_content/icons/c3fb6593efe54172d6832cc5dac4b9a4.jpg",  # Igneous Hammer Adept
    "/common/destiny2_content/icons/626846566f347b1b631321b2ce21e099.jpg",  # The Messenger
    "/common/destiny2_content/icons/6f025b0f11d69548c8051d47ef9f7b28.jpg",  # Messenger Adept
    "/common/destiny2_content/icons/34fa2107bfddfbe6c559de876a3aac55.jpg",  # Chattering Bone
    "/common/destiny2_content/icons/7741689cbc1102aa9fc742b33a106f19.jpg",  # Fatebringer
]

BASE = "https://www.bungie.net"


def collect_paths() -> list[str]:
    paths: set[str] = set(EXTRA_WEAPON_ICONS)
    for src in (OFFICIAL_DART, WEB_FILTERS):
        if not src.is_file():
            continue
        text = src.read_text(encoding="utf-8")
        for m in re.finditer(
            r"/common/destiny2_content/icons/[A-Za-z0-9_.-]+\.(?:png|jpg|jpeg)",
            text,
        ):
            paths.add(m.group(0))
    return sorted(paths)


def download(path: str) -> bool:
    name = path.rsplit("/", 1)[-1]
    out = ICONS_DIR / name
    url = f"{BASE}{path}"
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            data = resp.read()
        if len(data) < 200:
            print(f"  skip (too small) {name}")
            return False
        out.write_bytes(data)
        print(f"  ok {name} ({len(data)} bytes)")
        return True
    except Exception as e:  # noqa: BLE001
        print(f"  fail {name}: {e}")
        return False


def write_generated(basenames: list[str]) -> None:
    lines = [
        "// GENERATED by tool/fetch_bungie_content_icons.py — do not edit by hand.",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "/// Basenames under [kBungieContentAssetDir] that ship with this package.",
        "const Set<String> kBungieContentLocalBasenames = {",
    ]
    for b in basenames:
        lines.append(f"  '{b}',")
    lines += [
        "};",
        "",
    ]
    GEN.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {GEN.relative_to(ROOT)} ({len(basenames)} basenames)")


def main() -> None:
    ICONS_DIR.mkdir(parents=True, exist_ok=True)
    paths = collect_paths()
    print(f"fetching {len(paths)} CDN paths…")
    for p in paths:
        download(p)
    basenames = sorted(
        p.name
        for p in ICONS_DIR.iterdir()
        if p.suffix.lower() in {".png", ".jpg", ".jpeg"}
    )
    write_generated(basenames)
    print(f"done — {len(basenames)} local icons in {ICONS_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
